<?php declare(strict_types = 1);

/**
 * @file
 * Functions to support theming in the Tripal Cultivate Base Theme theme.
 */


/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function trpcultivatetheme_preprocess_html(array &$variables): void {

  // Ensure the colour-related CSS variables get set.
  // Convert custom hex to hsl so we can use the hue value
  $brand_color_hex = theme_get_setting('base_primary_color') ?? '#3C8700';
  [$h, $s, $l] = _olivero_hex_to_hsl($brand_color_hex);

  $variables['html_attributes']->setAttribute('style', "--color--primary-hue:$h;--color--primary-saturation:$s%;--color--primary-lightness:$l");

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function trpcultivatetheme_preprocess_page(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function trpcultivatetheme_preprocess_node(array &$variables): void {

}

/**
 * Implement hook_theme_suggestions_block_alter() for tiles section templates.
 *
 * @see Olivero hook_theme_suggestions_block_alter implementation.
 */
function trpcultivatetheme_theme_suggestions_block_alter(&$suggestions, array $variables) {
  if (!empty($variables['elements']['#id'])) {
    /** @var \Drupal\block\BlockInterface $block */
    $block = \Drupal::entityTypeManager()
      ->getStorage('block')
      ->load($variables['elements']['#id']);

    if ($block) {
      $region = $block
        ->getRegion();

      // Add tile content and markup into a tile region that uses the prefix
      // trpcultivatetheme (theme name) keyword only.
      $def_theme = \Drupal::config('system.theme')
        ->get('default');
            
      $regions = system_region_list($def_theme);
      foreach($regions as $region_name => $_) {
        if (preg_match('/^' . $def_theme . '/', $region_name) && $region == $region_name) {
          $suggestions[] = 'block__' . $region_name;
          $suggestions[] = 'block__' . str_replace('_', '-', $region_name) . '__block';
          $suggestions[] = 'block__' . $region_name . '__' . 'plugin_id' . '__' . $variables['elements']['#plugin_id'];
          $suggestions[] = 'block__' . $region_name . '__' . 'id' . '__' . $variables['elements']['#id'];
        }
      }  
    }  
  }
}

/**
 * Implements hook_preprocess_block().
 *
 * Creates a theme variable that contains sanitized/raw unformatted values of fields
 * in addition to formatted values.
 */
function trpcultivatetheme_preprocess_block(&$variables) {
  if (!empty($variables['elements']['#id'])) {
    /** @var \Drupal\block\BlockInterface $block */
    $block = \Drupal::entityTypeManager()
      ->getStorage('block')
      ->load($variables['elements']['#id']);
    
    // Only theme trpcultivatetheme specific content.
    $def_theme = \Drupal::config('system.theme')
      ->get('default');
      
    // Fetch the region this block content was placed in.
    // This will be the theme variable name.
    $content_region_placement = $block->getRegion();
    
    if (preg_match('/^' . $def_theme . '/', $content_region_placement)) {  
      // Array to hold the raw value.
      $tile_raw_content = [];

      // Fields title, link + link text, cover image and bgcolor that
      // make up a tile in the frontend.
      $fields = [
        'title' => 'text',     // Tile title: text value.
        'link'  => 'link',     // Tile link: url + link text object.
        'coverimg' => 'image', // Tile cover image: image object.,
        'bgcolor'  => 'color',  // Tile background color: text/string value.
      ];

      foreach($fields as $field_name => $field_type) {
        $field_machine_name = $def_theme . '_tile_' . $field_name;  
        
        // Ensure that only tile block contents get processed.
        $block_dependencies = $block->getDependencies();
       
        if (isset($block_dependencies['content'][0]) && str_contains($block_dependencies['content'][0], 'trpcultivatetheme_tile_block')) {
          // Only when content is block content of type trpcultivatetheme_tile_block.

          // Field formatted #content values.
          $field_content = $variables['content']['#block_content']
            ->get($field_machine_name)->first();

          $field_value = '';

          if ($field_content) {
            if ($field_type == 'link') {
              // Link object:
              // Fetch the link url and link title text.
              $link_url = $field_content->getUrl()->toString();  
              $link_txt = $field_content->get('title')->getValue();
              $field_value = ['url' => $link_url, 'text' => $link_txt];
            }
            elseif ($field_type == 'image') {
              // Image object. 
              // Fetch image uri.
              $field_value = $field_content->entity
                ->createFileUrl();
            }
            elseif ($field_type == 'color') {
              // Color type, provide hex value and rgb equivalent.
              $hex = $field_content->value;
              
              $rgb = '';
              if (preg_match('/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/', $hex)) {
                $c = sscanf($hex, '#%02x%02x%02x');
                $rgb = implode(',', $c); 
              }

              $field_value = ['hex' => $hex, 'rgb' => $rgb];
            }
            else {
              // Text value
              $field_value = $field_content->value;
            }

            $raw_value = (empty($field_value)) ? '' : $field_value;
            $tile_raw_content[ $field_name ] = $raw_value;
          }
        
          // Exclude tile block content label.
          unset($variables['label']);
        }
      }

      // Create a theme variable:
      $variables[ $content_region_placement ] = $tile_raw_content;
      $variables['content_region'] = $content_region_placement; 

      // @debug dpm($variables);
    }    
  }
}