<?php

/**
 * @file
 * Install, update, and uninstall functions for Tripal Cultivate Theme Companion.
 */

use Drupal\block_content\Entity\BlockContentType;
use Drupal\Core\Entity\Entity\EntityFormDisplay;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_install().
 * Create block content type and fields used by the tile layout in the theme companion.
 */
function trpcultivatetheme_companion_install() {
  $content_schema = [
    // TILES:
    'trpcultivatetheme_tile_block' => [
      'block' => [
        'label' => 'Tripal Cultivate Theme Tile Block',
        'description' => 'This block content type is used to insert content into tiles'
      ],
      'fieldset' => [
        'trpcultivatetheme_tile_title'    => [
          'label' => 'Tile Title Text',
          'weight' => 0,
          'type' => [
            'storage' => 'string',
            'display' => 'basic_string',
            'form' => 'string_textarea'
          ],
          'settings' => [
            'placeholder' => 'eg. New Bioinformatics Tools Launch',
            'max_length' => 255
          ]
        ],
        'trpcultivatetheme_tile_link'     => [
          'label' => 'Tile Link (URL)',
          'weight' => 1,
          'type' => [
            'storage' => 'link',
            'display' => 'uri_link', 
            'form' => 'link_default'
          ],
          'settings' => [
            'link_type' => 'url',
            'protocols' => ['http', 'https']
          ] 
        ],
        'trpcultivatetheme_tile_coverimg' => [
          'label' => 'Tile Cover Image (JPG, GIF, WEBP or PNG)',
          'weight' => 2,
          'type' => [
            'storage' => 'image',
            'display' => 'file_uri',
            'form' => 'image_image'
          ],
          'settings' => ['file_extensions' => 'jpg jpeg gif webp png']  
        ],
        'trpcultivatetheme_tile_bgcolor'  => [
          'label' => 'Tile Background Colour',
          'weight' => 3,
          'type' => [
            'storage' => 'string',
            'display' => 'basic_string',
            'form' => 'string_textarea'
          ],
          'settings' => [
            'placeholder' => 'eg. #000000 for black',
            'max_length' => 7
          ] 
        ],
      ],
    ],

    // MAIN CONTENT:
    'trpcultivatetheme_content_block' => [
      'block' => [
        'label' => 'Tripal Cultivate Theme Main Content Block',
        'description' => 'This block content type is used to insert content into main content section'
      ],
      'fieldset' => [
        'trpcultivatetheme_content_title1' => [
          'label' => 'Left Article: Title Text',
          'weight' => 0,
          'type' => [
            'storage' => 'string',
            'display' => 'basic_string',
            'form' => 'string_textarea'
          ],
          'settings' => [
            'placeholder' => 'eg. KnowPulse: A Web-Resource Focused on Diversity Data for Pulse Crop Improvement',
            'max_length' => 255
          ]
        ],
      ],
    ],
  ];
  
  // Create content block.
  foreach ($content_schema as $bundle => $schema) {
    // All content assets (field and storage) go into this bundle.
    // Prepare storage, containers and configuration for the field.

    // Ensure that block type does not exists.
    $block_exists = BlockContentType::load($bundle);
    
    if (!$block_exists) {
      // Create the block type.
      // @see admin/structure/block-content.
      $block = $schema['block'] + ['id' => $bundle]; 

      BlockContentType::create($block)
        ->save();

      $block_type = [
        'targetEntityType' => 'block_content',
        'bundle'  => $bundle,
        'status' => TRUE,
        'mode'  => 'default',
      ];
      
      // Create block form display configuration.
      // @see admin/structure/block-content - Manage Form tab.
      $tile_block_form_config = EntityFormDisplay::create($block_type); 

      // Create block type display configuration.
      // @see admin/structure/block-content - Manage Display tab.
      $tile_block_display_config = EntityViewDisplay::create($block_type);
      
      foreach($schema['fieldset'] as $field_name => $field_prop) {
        // Create storage.
        FieldStorageConfig::create([
          'field_name' => $field_name,
          'entity_type' => 'block_content',
          'type' => $field_prop['type']['storage'],
          'settings' => $field_prop['settings']
        ])
          ->save();

        // Attach to type.
        FieldConfig::create([
          'field_name' => $field_name,
          'entity_type' => 'block_content',
          'bundle' => $bundle,
          'label' => $field_prop['label']
        ])
          ->save();

        // Enable field.
        $field_setting = [
          'weight'  => $field_prop['weight'],
          'hidden' => FALSE,
          'label' => 'hidden',
          'settings' => $field_prop['settings']
        ];

        // Form:
        $field_setting['type'] = $field_prop['type']['form'];
        $tile_block_form_config->setComponent($field_name, $field_setting)
          ->save();

        // Display:
        $field_setting['type'] = $field_prop['type']['display'];
        $tile_block_display_config->setComponent($field_name, $field_setting)
          ->save();

        unset($tile_block_form_config, $tile_block_display_config);
      }
    }
  }
}