<?php

/**
 * @file
 * Install, update, and uninstall functions for Tripal Cultivate Theme Companion.
 */

use Drupal\block_content\Entity\BlockContentType;
use Drupal\Core\Entity\Entity\EntityFormDisplay;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_enable().
 * Create block content type and fields used by the tile layout in the theme companion.
 */
function trpcultivatetheme_companion_enable() {
  // All content assets (field and storage) go into this bundle.
  $tile_content = 'trpcultivatetheme_tile_block';

  // Tile field schema.
  // Field name length cannot be more than 32 chars (prefix is 23 chars).
  // Field types:
  // https://www.drupal.org/docs/drupal-apis/entity-api/fieldtypes-fieldwidgets-and-fieldformatters
  $field_prefix = 'trpcultivatetheme_tile_';
  $tile_fields = [
    // Tile title text.
    $field_prefix . 'title' => [
      'label' => 'Tile Title Text',
      'weight' => 0,
      'type' => [
        'storage' => 'string',
        'display' => 'basic_string',
        'form' => 'string_textarea'
      ],
      'settings' => [
        'placeholder' => 'eg. New Bioinformatics Tools Launch',
        'max_length' => 255
      ] 
    ],
    
    // Tile link (url) and text combo.
    $field_prefix . 'link' => [
      'label' => 'Tile Link (URL)',
      'weight' => 1,
      'type' => [
        'storage' => 'link',
        'display' => 'uri_link', 
        'form' => 'link_default'
      ],
      'settings' => [
        'link_type' => 'url',
        'protocols' => ['http', 'https']
      ] 
    ],

    // Tile cover image.
    $field_prefix . 'coverimg' => [
      'label' => 'Tile Cover Image (JPG, GIF, WEBP or PNG)',
      'weight' => 2,
      'type' => [
        'storage' => 'image',
        'display' => 'file_uri',
        'form' => 'image_image'
      ],
      'settings' => ['file_extensions' => 'jpg jpeg gif webp png']
    ],

    // Tile background colour.
    $field_prefix . 'bgcolor' => [
      'label' => 'Tile Background Colour',
      'weight' => 3,
      'type' => [
        'storage' => 'string',
        'display' => 'basic_string',
        'form' => 'string_textarea'
      ],
      'settings' => [
        'placeholder' => 'eg. #000000 for black',
        'max_length' => 7
      ]
    ],

    // Additional fields here.
  ];
  

  // Prepare storage, containers and configuration for the field.

  // Ensure that block type does not exists.
  $block_exists = BlockContentType::load($tile_content);

  if (!$block_exists) {
    // Create the block type.
    // @see admin/structure/block-content.
    $tile_block = [
      'id' => $tile_content,
      'label' => 'Tripal Cultivate Theme Tile Block',
      'description' => 'This block content type is used to insert content into tiles'
    ];

    BlockContentType::create($tile_block)
      ->save();

    $block_type = [
      'targetEntityType' => 'block_content',
      'bundle'  => $tile_content,
      'status' => TRUE,
      'mode'  => 'default',
    ];

    // Create block form display configuration.
    // @see admin/structure/block-content - Manage Form tab.
    $tile_block_form_config = EntityFormDisplay::create($block_type); 

    // Create block type display configuration.
    // @see admin/structure/block-content - Manage Display tab.
    $tile_block_display_config = EntityViewDisplay::create($block_type);

    foreach($tile_fields as $field_name => $fieldprop) {
      // Create storage.
      FieldStorageConfig::create([
        'field_name' => $field_name,
        'entity_type' => 'block_content',
        'type' => $fieldprop['type']['storage'],
        'settings' => $fieldprop['settings']
      ])
        ->save();

      // Attach to type.
      FieldConfig::create([
        'field_name' => $field_name,
        'entity_type' => 'block_content',
        'bundle' => $tile_content,
        'label' => $fieldprop['label']
      ])
        ->save();

      // Enable field.
      $field_setting = [
        'weight'  => $fieldprop['weight'],
        'hidden' => FALSE,
        'label' => 'hidden',
        'settings' => $fieldprop['settings']
      ];

      $field_setting['type'] = $fieldprop['type']['form'];
      $tile_block_form_config->setComponent($field_name, $field_setting)
        ->save();

      $field_setting['type'] = $fieldprop['type']['display'];
      $tile_block_display_config->setComponent($field_name, $field_setting)
        ->save();
    }
  }
}