<?php
use \Drupal\block\Entity\Block;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_form_alter().
 *
 * This will add JS color picker library to form that add/edit tile block content
 * in the dependent theme - Tripal Cultivate Theme.
 *
 * The color picker will launch a color picker window to allow user to pick a color
 * that will be transferred to the field in hex code value.
 *
 * @see libraries.
 */
function trpcultivatetheme_companion_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $tile_block = 'block_content_trpcultivatetheme_tile_block';

  if ($form_id == $tile_block . '_form' || $form_id == $tile_block . '_edit_form') {
    // When the form is to add or edit a tile block content, attach color picker library.
    $form['#attached']['library'][] = 'trpcultivatetheme_companion/trpcultivatetheme-color-picker';
    $form['trpcultivatetheme_tile_bgcolor']['#attributes']['style'] = 'width: 200px';
  } 
}

/**
 * Implements hook_block_access().
 *
 * Remind user when adding a non-compatible content into tiles region.
 * @see api.drupal.org/api/drupal/core%21modules%21block%21block.api.php/function/hook_block_access/10
 */
function trpcultivatetheme_companion_block_access(Block $block, $operation, AccountInterface $account) {
  // Fetch all the regions of trpcultivatetheme (default theme) and filter out other
  // regions defined by the base theme. Focus on tile regions only.

  $def_theme = \Drupal::config('system.theme')
    ->get('default');
            
  $regions = system_region_list($def_theme);
  
  // Extract only the trpcultivatetheme_tiles custom regions.
  $trpcultivatetheme_tiles_regions = []; 
  
  foreach($regions as $region_name => $_) {
    if (preg_match('/^' . $def_theme . '_tiles/', $region_name)) {
      array_push($trpcultivatetheme_tiles_regions, $region_name);
    }
  } 
  
  // The region the content is about to be placed.
  $block_region = $block->getRegion();

  if ($block_region && in_array($block_region, $trpcultivatetheme_tiles_regions) && $operation == 'update') {
    // When updating a region by placing a content block into any of the tiles region.
    
    // The id of the content.
    $block_id = $block->getPluginId();

    if ($block_id) {
      // @debug dpm($block);

      // Tile content is a block content type and id is a hash value
      // ie. block_content:58dad12f-a9e4-4305-a082-d370ae079137.
      // @see hook_install().
      // Content is block_content plus unique id number since multiple instance can be created.
    
      if (!preg_match('/^block_content:/', $block_id)) {  
        // The content id does not match the tripalcultivatetheme tile content id format.
        
        $error_message = 'A non-compatible content was added to Tripal Cultivate Theme Tiles region. ';
        $error_message .= 'BLOCK: '. ucwords(str_replace('_', ' ', $block_id)) . ' REGION: ' . ucwords(str_replace('_', ' ', $block_region));

        // Logs an error
        \Drupal::logger('trpcultivatetheme_companion')
          ->error($error_message);
        
        // Warns user.
        \Drupal::messenger()
          ->addWarning(t($error_message));
      } 
    }
  }
}